import Link from "next/link"

function BrandSymbol() {
  return <svg viewBox="0 0 64 64" className="h-12 w-12" aria-hidden="true"><rect x="5" y="10" width="44" height="32" rx="6" fill="#2563eb" stroke="white" strokeWidth="3"/><path d="M10 47h34" stroke="#fbbf24" strokeWidth="5" strokeLinecap="round"/><path d="M15 28c6-4 11-4 17 0v13c-6-4-11-4-17 0V28Zm17 0c6-4 11-4 17 0v13c-6-4-11-4-17 0V28Z" fill="white" stroke="#0f3f86" strokeWidth="1.5"/><path d="m51 8 2 4 5 .7-3.6 3.4.9 4.9-4.3-2.3-4.3 2.3.9-4.9-3.6-3.4 5-.7 2-4Z" fill="#fbbf24"/><circle cx="55" cy="29" r="5" fill="#ec4899"/></svg>
}

export function SiteFooter() {
  return <footer className="border-t border-blue-900 bg-slate-950 text-white"><div className="container mx-auto grid gap-8 px-4 py-10 md:grid-cols-3"><div><div className="flex items-center gap-3"><BrandSymbol /><div><p className="font-black">PEP PRACTICE <span className="text-pink-400">— GRADE 4</span></p><p className="text-xs text-slate-300">Practice • Review • Confidence</p></div></div><p className="mt-4 text-sm text-slate-300"><span className="text-slate-400">by</span> <span className="font-semibold text-white">Shazonique&apos;s Inspiration</span></p><p className="mt-2 text-xs leading-relaxed text-slate-400">Different grade. Different developmental stage. Same PEP PRACTICE.</p></div><div><h3 className="text-sm font-bold uppercase tracking-wider text-slate-200">Quick Links</h3><div className="mt-4 grid gap-2 text-sm text-slate-300"><Link href="/language-arts" className="hover:text-white">Start Free Practice</Link><Link href="/pricing" className="hover:text-white">View Pricing</Link><Link href="/login" className="hover:text-white">Sign In</Link><Link href="/register" className="hover:text-white">Create Account</Link></div></div><div><h3 className="text-sm font-bold uppercase tracking-wider text-slate-200">Grade 4 Learning</h3><p className="mt-4 text-sm leading-relaxed text-slate-300">Language Arts, Mathematics, Performance Tasks and mock-style practice in one focused online Grade 4 experience.</p><Link href="/about" className="mt-3 inline-block text-sm font-semibold text-blue-300 hover:text-blue-200">About PEP PRACTICE</Link></div></div><div className="border-t border-white/10 px-4 py-5 text-center text-xs text-slate-400">© {new Date().getFullYear()} Shazonique&apos;s Inspiration. PEP PRACTICE — Grade 4.</div></footer>
}
