export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://grade-4-pep.vercel.app"
export const PRODUCT_CODE = process.env.NEXT_PUBLIC_PRODUCT_CODE || "grade4"
export const PRODUCT_LABEL = "Grade 4 PEP"
export const WHATSAPP_NUMBER = "18765055212"
export const WHATSAPP_DISPLAY = "876-505-5212"
